server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: chenxinshuai

mybatis:
  # 指定将会在resource下的mapper文件夹下创建xxx.xml的映射文件
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lun.springcloud.entities